books/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout')
]

books/bookLibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework import routers
from . import views


app_name = 'BookLibrary'
"""
router = routers.DefaultRouter()
router.register(r'book', views.BookViewSet)
"""

urlpatterns = [
    #path('', include(router.urls)),
    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', views.index, name='home'),
    path('upload/', views.upload, name='upload-book'),
    path('delete/<int:id>', views.book_delete, name='delete-book'),
    path('details/<int:id>', views.details, name='details'),
    path('edit/<int:id>', views.edit, name='edit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookLibrary.urls')),
    path('accounts/', include('accounts.urls')),
]

books/accounts/models.py
from django.db import models

# Create your models here.

books/bookLibrary/models.py
from django.db import models
from django.contrib.auth.models import User


class Book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    author = models.CharField(max_length=150)
    book_name = models.CharField(max_length=200)
    cover_image = models.ImageField(upload_to='img', null=True, blank=True)
    description = models.CharField(max_length=450)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.book_name + "Uploaded by " + self.user.username

books/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

books/bookLibrary/forms.py
from django import forms
from .models import Book


class BookUpload(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Book
        fields = ('book_name', 'author', 'cover_image', 'description')

books/accounts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse

from .forms import RegistrationForm


def register(request):
    if request.method == 'POST':
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('accounts:user_login')
    else:
        user_form = RegistrationForm()
    return render(request, 'accounts/register.html', {'user_form': user_form})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        # Authenticate user from Database
        user = authenticate(username=username, password=password)

        # if user is authenticated
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('BookLibrary:home'))
            else:
                return HttpResponse("Account is Inactive")

        else:
            return HttpResponse("Invalid login details")

    else:
        return render(request, 'accounts/login.html', {})


@login_required()
def user_logout(request):
    logout(request)
    return redirect(reverse('accounts:user_login'))

books/bookLibrary/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from .models import Book
from .forms import BookUpload

#from rest_framework import viewsets
#from .serializers import BookSerializer


@login_required()
def index(request):
    try:
        books = Book.objects.all()
    except Book.DoesNotExist:
        books = None

    return render(request, 'bookLibrary/index.html', {'books': books})


"""
# for View Rest API
class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
"""


@login_required()
def upload(request):
    if request.method == 'POST':
        book_form = BookUpload(data=request.POST)
        if book_form.is_valid():
            bf = book_form.save(commit=False)
            bf.user = request.user
            if 'cover_image' in request.FILES:
                bf.cover_image = request.FILES['cover_image']
            bf.save()

            return redirect(reverse('BookLibrary:home'))

        return HttpResponse(request, "Invalid Form!!")

    book_form = BookUpload()
    return render(request, 'bookLibrary/upload.html', {'form': book_form})


@login_required()
def details(request, id):
    book_id = int(id)
    try:
        book_det = Book.objects.get(id=book_id)
    except Book.DoesNotExist:
        return redirect('BookLibrary:home')
    return render(request, 'bookLibrary/details.html', {'book_det': book_det})


@login_required()
def edit(request, id):
    book_id = int(id)
    try:
        book_upd = Book.objects.get(id=book_id)
    except Book.DoesNotExist:
        return redirect('BookLibrary:home')

    book_form = BookUpload(request.POST or None, instance=book_upd)
    if book_form.is_valid():
        book_form.save()
        return redirect('BookLibrary:home')
    return render(request, 'bookLibrary/upload.html', {'form': book_form})


@login_required()
def book_delete(request, id):
    book_id = int(id)
    try:
        book_del = Book.objects.get(id=book_id)
    except Book.DoesNotExist:
        return redirect('BookLibrary:home')

    book_del.delete()
    return redirect('BookLibrary:home')

books/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body_block %}
<div class="jumbotron">
    <div class="container">
    <h1>Please login here..</h1>
    <form action="{% url 'accounts:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username">

        <label for="password">Password: </label>
        <input type="password" name="password">

        <input type="submit" class="btn btn-default" value="Login">
    </form>
    </div>
   </div>
{% endblock %}

books/templates/accounts/register.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body_block %}
    <h1>For Registration! please fill out this form</h1>
    <form method="POST">
    {% csrf_token %}
    {% bootstrap_form user_form %}
    <input type="submit" class="btn btn-default" value="Register">
    </form>
{% endblock %}

books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Book Library</title>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
      integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
      integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Solway:500&display=swap" rel="stylesheet">

    <meta charset="UTF-8">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'BookLibrary:home' %}">Book Library</a> </li>
                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'BookLibrary:upload-book' %}">Upload Book</a> </li>
                {% else %}
                    <li><a class="navbar-brand" href="{% url 'accounts:user_login' %}">Login</a> </li>
                    <li><a class="navbar-link" href="{% url 'accounts:register' %}">Register</a> </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
            <li><a class="navbar-link" href="{% url 'accounts:logout' %}">Logout</a> </li>
            </ul>
            {% endif %}
        </div>
    </nav>

<div class="container" style="height: max-content;">
        {% block body_block %}
        {% endblock %}

</div>

</body>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.4/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>
</html>

books/templates/bookLibrary/details.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
    <div class="jumbotron">
        <div class="container">
            <img class="bd-placeholder-img card-img-top" width="100%" height="500" src="{{ book_det.cover_image.url }}" >
            <h1>{{ book_det.book_name }}</h1>
            <h6>{{ book_det.author }}</h6>
            <p>{{ book_det.description }}</p>
        </div>
    </div>
    {% endblock %}

books/templates/bookLibrary/index.html
<!doctype html>
{% extends 'base.html' %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/album/">

    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="https://getbootstrap.com/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.4/examples/album/album.css" rel="stylesheet">
  </head>
  <body>
{% block body_block %}

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1>Album example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <a href="{% url 'BookLibrary:upload-book' %}" class="btn btn-primary my-2">Book Upload</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
      {% if books %}
      {% for b in books %}
        {% if b.is_approved %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            {% if b.cover_image %}
            <img class="bd-placeholder-img card-img-top" width="225" height="225" src="{{ b.cover_image.url }}" >
            {% endif %}
            <div class="card-body">
                <h2>{{ b.book_name }}</h2>
                <h6>Author: {{ b.author }}</h6>
              <p class="card-text">{{ b.description|truncatewords:20 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                    <a href="{% url 'BookLibrary:details' b.id %}">Details</a></button>
                  {% if b.user == request.user %}
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                    <a href="{% url 'BookLibrary:edit' b.id %}">Edit</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                    <a href="{% url 'BookLibrary:delete-book' b.id %}">Delete</a></button>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      {% endfor %}
      {% endif %}

      </div>
    </div>
  </div>

</main>
{% endblock %}

books/templates/bookLibrary/upload.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Upload">
    </form>
{% endblock %}